name: demo1
on : workflow_dispatch
jobs:
    This-is-my-first-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo " Welcome to gut Hub Actions:Mr. Shrinivas"
            
        
        
    
